apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-wait-before-ready: "true"
        config.linkerd.io/opaque-ports: "5432"
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: BACKEND/IMAGE
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configuration
                  key: database.url
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: nats.url
            - name: NATS_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: nats.subject
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-secrets
                  key: bot-token
            - name: CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-secrets
                  key: chat-id

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    cloud.google.com/backend-config: '{"default" :"healthcheck"}'
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor-metrics
  labels:
    release: "kube-prometheus-stack"
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: "/actuator/prometheus"
