apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: BACKEND/IMAGE
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 50
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configuration
                  key: database.url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default" :"healthcheck"}'
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: healthcheck
spec:
  healthCheck:
    timeoutSec: 15
    type: HTTP
    requestPath: /health
    port: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor-metrics
  labels:
    release: "kube-prometheus-stack"
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: "/actuator/prometheus"
