apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: BACKEND/IMAGE
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 50
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configuration
                  key: database.url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend-service
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8080
      name: backend-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor-metrics
spec:
  selector:
    matchLabels:
      app: backend-service
  endpoints:
    - port: backend-metrics
      path: /metrics
