apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-secrets.yaml
  - database-config.yaml
  - statefulset.yaml
  - rollout-deployment.yaml
  - analysistemplate.yaml
  - ingress.yaml
  - telegram-config.yaml
  - telegram-secrets.yaml
images:
  - name: BACKEND/IMAGE
    newName: gcr.io/dwk-gke-416915/backend