apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-secrets.yaml
- database-config.yaml
- statefulset.yaml
- deployment.yaml
- analysistemplate.yaml
- ingress.yaml
- telegram-config.yaml
- telegram-secrets.yaml
- backendconfig.yaml
images:
- name: BACKEND/IMAGE
  newName: gcr.io/dwk-gke-450416/backend

