apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - postgres-secrets.yaml
  - database-config.yaml
  - statefulset.yaml
images:
  - name: BACKEND/IMAGE
    newName: gcr.io/dwk-gke-416915/backend